/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    AboutMyWork: typeof import('./components/AboutMyWork.vue')['default']
    ActionBtn: typeof import('./components/Buttons/ActionBtn.vue')['default']
    ActionBtnSecond: typeof import('./components/Buttons/ActionBtnSecond.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BtnDiploma: typeof import('./components/Buttons/BtnDiploma.vue')['default']
    Contact: typeof import('./components/Contact.vue')['default']
    FigureItOutTogether: typeof import('./components/AboutWorkBlock/FigureItOutTogether.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MainInfo: typeof import('./components/MainInfo.vue')['default']
    MyDiplom: typeof import('./components/MyDiplom.vue')['default']
    Quote: typeof import('./components/Quote.vue')['default']
    Review: typeof import('./components/Review.vue')['default']
    ReviewSec: typeof import('./components/slider/ReviewSec.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Services: typeof import('./components/Services.vue')['default']
    ServicesBlock: typeof import('./components/servicesBlock/ServicesBlock.vue')['default']
    Slide: typeof import('./components/slider/Slide.vue')['default']
    SliderControl: typeof import('./components/slider/SliderControl.vue')['default']
    SocialBtn: typeof import('./components/Buttons/SocialBtn.vue')['default']
    YourAddressingMe: typeof import('./components/AboutWorkBlock/YourAddressingMe.vue')['default']
    YouWillLearn: typeof import('./components/AboutWorkBlock/YouWillLearn.vue')['default']
  }
}
